suspicious_words = [
    "to do",
    "todo",
    "fix",
    "fix me",
    "fixme"
    "corrigir",
    " bug ",
    "not work",
    "não funciona",
    "temporarily",
    "temporário",
    "temporario",
    "issue",
    "workaround",
    "gambiarra",
    "dont modify",
    "don't modify",
    "do not modify",
    "do not edit",
    "don't edit",
    "dont edit",
    "nao altere",
    "não altere",
    "não modifique"
    "nao modifique",
    "nao mexa"
    "não mexa",
    "atenção",
    "atençao",
    "warning",
    "nao sei",
    "não sei",
    "not sure"
]