###
### DO NOT MODIFY THIS FILE.  THIS FILE HAS BEEN AUTOGENERATED
###

FROM mongo:3.4.18-jessie

CMD ["mongod", "--nojournal", "--noprealloc", "--smallfiles"]

# Comentário por Mateus Medeiros
# SM05 linha 2